### ISSUE TITLE
Detects iPhone XR simulator but not device

### ISSUE THREAD

**Issue by btknorr** [Topener/ti.detect#2]
We have many users with iPhone XRs and while this module correctly detects an XR using the simulator it doesn't detect actual XR devices.  Unfortunately we personally do not have an XR device and cannot debug the issue, so we were hoping the issue could be debugged and fixed here instead.  Thanks!

**Comment by Topener** [comment]
Thanks for submitting an issue! Released 1.0.2 to fix the problem
